/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import CRUD.Database;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ACER
 */
public class Form_umkm extends javax.swing.JFrame {
    
    private final Database dbConnect;
    public Form_umkm() {
        initComponents();
        dbConnect = new Database();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label4 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Combobox1 = new javax.swing.JComboBox<>();
        Edit2 = new javax.swing.JTextField();
        ButtonI = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        ButtonU = new javax.swing.JButton();
        ButtonB = new javax.swing.JButton();
        ButtonD = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        ScrollPanel = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        Label2 = new javax.swing.JLabel();
        Edit1 = new javax.swing.JTextField();
        Edit3 = new javax.swing.JTextField();
        Edit4 = new javax.swing.JTextField();
        Edit5 = new javax.swing.JTextField();
        Label5 = new javax.swing.JLabel();
        Edit6 = new javax.swing.JTextField();
        Label6 = new javax.swing.JLabel();
        Edit7 = new javax.swing.JTextField();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        Label4.setText("Nama Pemilik:");

        Label3.setText("Cari Nama:");

        Edit2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Edit2KeyPressed(evt);
            }
        });

        ButtonI.setText("Insert");
        ButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIActionPerformed(evt);
            }
        });

        ButtonC.setText("Clear");
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });

        ButtonU.setText("Update");
        ButtonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUActionPerformed(evt);
            }
        });

        ButtonB.setText("Back");
        ButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBActionPerformed(evt);
            }
        });

        ButtonD.setText("Delete");
        ButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDActionPerformed(evt);
            }
        });

        Label1.setText("Kode UMKM:");

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode UMKM", "Nama UMKM", "Nama Pemilik", "Deskripsi", "Alamat", "Kode Penduduk", "Kode Industri"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        ScrollPanel.setViewportView(Table1);

        Label2.setText("Nama UMKM:");

        Label5.setText("Deskripsi:");

        Label6.setText("Alamat:");

        Label7.setText("Kode Industri:");

        Label8.setText("Kode Penduduk:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Edit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Label4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Label1)
                                                    .addComponent(Label2))
                                                .addComponent(Label5, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Edit4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Edit3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Edit5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(30, 30, 30)
                                    .addComponent(Label8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Edit7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(277, 277, 277)
                                            .addComponent(Label6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Edit6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(ButtonI)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(ButtonU)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(ButtonD)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(ButtonC)
                                                    .addGap(18, 18, 18))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGap(277, 277, 277)
                                                    .addComponent(Label7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ButtonB))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(Label3)
                                .addGap(18, 18, 18)
                                .addComponent(Edit2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addComponent(ScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label2)
                    .addComponent(Edit7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edit4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label4)
                            .addComponent(Label7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edit5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonI)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonU)
                        .addComponent(ButtonD)
                        .addComponent(ButtonC)
                        .addComponent(ButtonB)))
                .addGap(18, 18, 18)
                .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label3)
                    .addComponent(Edit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Edit2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Edit2KeyPressed
        // TODO add your handling code here:
        DefaultTableModel table1 = (DefaultTableModel) Table1.getModel();
        table1.setRowCount(0);
        dbConnect.searchTableLike((DefaultTableModel)Table1.getModel(), "umkm", Edit2.getText());
    }//GEN-LAST:event_Edit2KeyPressed

    private void ButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel table1 = (DefaultTableModel) Table1.getModel();
            if(Edit1.getText().isEmpty() || Edit3.getText().isEmpty() || 
                    Edit4.getText().isEmpty() || Edit5.getText().isEmpty() || 
                    Edit6.getText().isEmpty() || Edit7.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Input tidak boleh kosong");
            }
            else{
                JOptionPane.showMessageDialog(null, (dbConnect.insertValueUMKM(
                        Edit1.getText(), Edit3.getText(), Edit4.getText(),
                        Edit5.getText(), Edit6.getText(), Edit7.getText(),
                        Combobox1.getSelectedItem().toString())));
                table1.setRowCount(0);
                dbConnect.getForeignKey(Combobox1, "jenis_industri", "Kode_industri");
                dbConnect.showtTable((DefaultTableModel)Table1.getModel(), "umkm");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_ButtonIActionPerformed

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        // TODO add your handling code here:
        Edit1.setText("");
        Edit2.setText("");
        Edit3.setText("");
        Edit4.setText("");
        Edit5.setText("");
        Edit6.setText("");
        Edit7.setText("");        
        Combobox1.setSelectedIndex(0);
    }//GEN-LAST:event_ButtonCActionPerformed

    private void ButtonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel table1 = (DefaultTableModel) Table1.getModel();
            if(Edit1.getText().isEmpty() || Edit3.getText().isEmpty() || 
                    Edit4.getText().isEmpty() || Edit5.getText().isEmpty() || 
                    Edit6.getText().isEmpty() || Edit7.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Input tidak boleh kosong");
            }
            else{
                JOptionPane.showMessageDialog(null, (dbConnect.updateValueUMKM(
                        Edit1.getText(), Edit3.getText(), Edit4.getText(),
                        Edit5.getText(), Edit6.getText(), Edit7.getText(),
                        Combobox1.getSelectedItem().toString())));
                table1.setRowCount(0);
                dbConnect.getForeignKey(Combobox1, "jenis_industri", "Kode_industri");
                dbConnect.showtTable((DefaultTableModel)Table1.getModel(), "umkm");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_ButtonUActionPerformed

    private void ButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBActionPerformed
        // TODO add your handling code here:
        new Form_Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonBActionPerformed

    private void ButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel table1 = (DefaultTableModel) Table1.getModel();
            if(Edit1.getText().isEmpty() || Edit3.getText().isEmpty() || 
                    Edit4.getText().isEmpty() || Edit5.getText().isEmpty() || 
                    Edit6.getText().isEmpty() || Edit7.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Input tidak boleh kosong");
            }
            else{
                JOptionPane.showMessageDialog(null, (dbConnect.deleteValueUMKM(Edit1.getText())));
                table1.setRowCount(0);
                dbConnect.getForeignKey(Combobox1, "jenis_industri", "Kode_industri");
                dbConnect.showtTable((DefaultTableModel)Table1.getModel(), "umkm");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_ButtonDActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
        int index = Table1.getSelectedRow();
        DefaultTableModel table1 = (DefaultTableModel) Table1.getModel();
        Edit1.setText(table1.getValueAt(index, 1).toString());
        Edit3.setText(table1.getValueAt(index, 2).toString());
        Edit4.setText(table1.getValueAt(index, 3).toString());
        Edit5.setText(table1.getValueAt(index, 4).toString());
        Edit6.setText(table1.getValueAt(index, 5).toString());
        Edit7.setText(table1.getValueAt(index, 6).toString());
        Combobox1.setSelectedItem(table1.getValueAt(index, 7));
    }//GEN-LAST:event_Table1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        dbConnect.getForeignKey(Combobox1, "jenis_industri", "Kode_industri");
        dbConnect.showtTable((DefaultTableModel)Table1.getModel(), "umkm");
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_umkm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_umkm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_umkm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_umkm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_umkm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonB;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonD;
    private javax.swing.JButton ButtonI;
    private javax.swing.JButton ButtonU;
    private javax.swing.JComboBox<String> Combobox1;
    private javax.swing.JTextField Edit1;
    private javax.swing.JTextField Edit2;
    private javax.swing.JTextField Edit3;
    private javax.swing.JTextField Edit4;
    private javax.swing.JTextField Edit5;
    private javax.swing.JTextField Edit6;
    private javax.swing.JTextField Edit7;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JTable Table1;
    // End of variables declaration//GEN-END:variables
}
