/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author ACER
 */
public class Form_Menu extends javax.swing.JFrame {
    public Form_Menu() {
        initComponents();
        this.setLocationRelativeTo(null); // moves windows to center   
    }

// private
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonJI = new javax.swing.JButton();
        buttonK = new javax.swing.JButton();
        buttonUMKM = new javax.swing.JButton();
        buttonJP = new javax.swing.JButton();
        buttonT = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonJI.setText("Form Jenis Industri");
        buttonJI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJIActionPerformed(evt);
            }
        });

        buttonK.setText("Form Konsumen");
        buttonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKActionPerformed(evt);
            }
        });

        buttonUMKM.setText("Form UMKM");
        buttonUMKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUMKMActionPerformed(evt);
            }
        });

        buttonJP.setText("Form Jual Produk");
        buttonJP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJPActionPerformed(evt);
            }
        });

        buttonT.setText("Form Transaksi");
        buttonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTActionPerformed(evt);
            }
        });

        buttonClose.setText("Keluar");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonJI)
                    .addComponent(buttonK)
                    .addComponent(buttonUMKM)
                    .addComponent(buttonJP)
                    .addComponent(buttonT)
                    .addComponent(buttonClose))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(buttonJI)
                .addGap(16, 16, 16)
                .addComponent(buttonK)
                .addGap(16, 16, 16)
                .addComponent(buttonUMKM)
                .addGap(16, 16, 16)
                .addComponent(buttonJP)
                .addGap(16, 16, 16)
                .addComponent(buttonT)
                .addGap(16, 16, 16)
                .addComponent(buttonClose)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonJIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJIActionPerformed
        new Form_jenis_industri().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_buttonJIActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void buttonJPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJPActionPerformed
        // TODO add your handling code here:
        new Form_jual_produk().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_buttonJPActionPerformed

    private void buttonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKActionPerformed
        // TODO add your handling code here:
        new Form_konsumen().setVisible(true);
        this.dispose();               
    }//GEN-LAST:event_buttonKActionPerformed

    private void buttonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTActionPerformed
        // TODO add your handling code here:
        new Form_transaksi().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_buttonTActionPerformed

    private void buttonUMKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUMKMActionPerformed
        // TODO add your handling code here:
        new Form_umkm().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_buttonUMKMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonJI;
    private javax.swing.JButton buttonJP;
    private javax.swing.JButton buttonK;
    private javax.swing.JButton buttonT;
    private javax.swing.JButton buttonUMKM;
    // End of variables declaration//GEN-END:variables
}
